/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package al_qalam;

import static al_qalam.Capital.conn;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad
 */
public class Bank extends javax.swing.JDialog {

    public static Connection conn() throws ClassNotFoundException,SQLException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url="jdbc:odbc:Al_Qalam";
        return DriverManager.getConnection(url,"sa","sa9" );
    }
    
    Connection cn;
    ResultSet rs;
    PreparedStatement ps;
    // <editor-fold defaultstate="collapsed" desc="focusGain">
        public void focusGain(JTextField txt,String s){
            if(txt.getText().equals(s)){
                txt.setText(null);
                txt.setForeground(Color.BLACK);
            }
            else{
                txt.setForeground(Color.BLACK);
                txt.selectAll();
            }
        }
    //    </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="focusLost">
        public void focusLost(JTextField txt,String s){
            if(txt.getText().equals("")){
                txt.setText(s);
                txt.setForeground(Color.GRAY);
            }
        }
    //    </editor-fold>

    /**
     * Creates new form bank
     * @param parent
     * @param modal
     */
    public Bank(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bankName_field = new javax.swing.JTextField();
        addBank_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 255));

        bankName_field.setForeground(java.awt.Color.gray);
        bankName_field.setText("Name");
        bankName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankName_fieldActionPerformed(evt);
            }
        });
        bankName_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankName_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankName_fieldFocusLost(evt);
            }
        });
        bankName_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bankName_fieldKeyTyped(evt);
            }
        });

        addBank_btn.setForeground(new java.awt.Color(0, 51, 102));
        addBank_btn.setText("Add Bank Account");
        addBank_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBank_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankName_field)
                    .addComponent(addBank_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBank_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankName_fieldActionPerformed
        try{
            if(bankName_field.getText().equals("") || bankName_field.getText().equals("Name")){
            }
            else{
                cn=conn();
                ps=cn.prepareStatement("INSERT INTO bankList VALUES('"+bankName_field.getText()+"')");
                ps.execute();
                cn.close();
            }
        }
        catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
        bankName_field.setText(null);
        bankName_field.requestFocus();
    }//GEN-LAST:event_bankName_fieldActionPerformed

    private void bankName_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankName_fieldFocusGained
        focusGain(bankName_field, "Name");
    }//GEN-LAST:event_bankName_fieldFocusGained

    private void bankName_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankName_fieldFocusLost
        focusLost(bankName_field, "Name");
    }//GEN-LAST:event_bankName_fieldFocusLost

    private void bankName_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankName_fieldKeyTyped
        if(bankName_field.getText().length()==50){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_bankName_fieldKeyTyped

    private void addBank_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBank_btnActionPerformed
        try{
            if(bankName_field.getText().equals("") || bankName_field.getText().equals("Name")){
            }
            else{
                cn=conn();
                ps=cn.prepareStatement("INSERT INTO bankList VALUES('"+bankName_field.getText()+"')");
                ps.execute();
                cn.close();
            }
        }
        catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
        bankName_field.setText(null);
        bankName_field.requestFocus();
    }//GEN-LAST:event_addBank_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bank dialog = new Bank(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBank_btn;
    private javax.swing.JTextField bankName_field;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
