/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package al_qalam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad
 */
public class Capital extends javax.swing.JDialog {

    public static Connection conn() throws ClassNotFoundException,SQLException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url="jdbc:odbc:Al_Qalam";
        return DriverManager.getConnection(url,"sa","sa9" );
    }
    
    Connection cn;
    ResultSet rs;
    PreparedStatement ps;
    String investmentMode="Cash";
    
    // <editor-fold defaultstate="collapsed" desc="focusGain">
        public void focusGain(JTextField txt,String s){
            if(txt.getText().equals(s)){
                txt.setText(null);
                txt.setForeground(Color.BLACK);
            }
            else{
                txt.setForeground(Color.BLACK);
                txt.selectAll();
            }
        }
    //    </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="focusLost">
        public void focusLost(JTextField txt,String s){
            if(txt.getText().equals("")){
                txt.setText(s);
                txt.setForeground(Color.GRAY);
            }
        }
    //    </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="getBankNames">
    public void getBankNames(JComboBox box) {
        try {
            box.removeAllItems();
            ps = cn.prepareStatement("SELECT bankName FROM bankList");
            rs = ps.executeQuery();
            while(rs.next()){
                box.addItem(rs.getString(1));
            }
        }
         catch(SQLException ex){
             JOptionPane.showMessageDialog(this, "Sql Exception");
         }
}
//    </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="getOwnerNames">
    public void getOwnerNames(JComboBox box) {
        try {
            box.removeAllItems();
            ps = cn.prepareStatement("SELECT name FROM owners");
            rs = ps.executeQuery();
            while(rs.next()){
                box.addItem(rs.getString(1));
            }
        }
         catch(SQLException ex){
             JOptionPane.showMessageDialog(this, "Sql Exception");
         }
}
//    </editor-fold>
    
    /**
     * Creates new form capital
     * @param parent
     * @param modal
     */
    public Capital(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            cn=conn();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Capital.class.getName()).log(Level.SEVERE, null, ex);
        }
        ownerName_comboBox.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGro = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Cheque3 = new javax.swing.JRadioButton();
        Cash3 = new javax.swing.JRadioButton();
        bankNameBox_owner = new javax.swing.JComboBox();
        investment_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ownerName_comboBox = new javax.swing.JComboBox();
        addOwner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(244, 244, 255));

        jPanel2.setBackground(new java.awt.Color(244, 244, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        Cheque3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGro.add(Cheque3);
        Cheque3.setText("Cheque");
        Cheque3.setOpaque(false);
        Cheque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cheque3ActionPerformed(evt);
            }
        });

        Cash3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGro.add(Cash3);
        Cash3.setSelected(true);
        Cash3.setText("Cash");
        Cash3.setBorder(null);
        Cash3.setOpaque(false);
        Cash3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash3ActionPerformed(evt);
            }
        });

        bankNameBox_owner.setEnabled(false);

        investment_field.setForeground(java.awt.Color.gray);
        investment_field.setText("Investment");
        investment_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                investment_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                investment_fieldFocusLost(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Define The Owner");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(89, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cash3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cheque3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addComponent(investment_field)
                    .addComponent(bankNameBox_owner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownerName_comboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerName_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investment_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cash3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cheque3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bankNameBox_owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addOwner.setText("Add Investment");
        addOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addOwner)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
float balanceCashBook,balanceChequeBook,bankBalanceOwner;
int bankIdOwner;
    private void addOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnerActionPerformed
        try{
            if(investment_field.getText().equals("") || investment_field.getText().equals("Investment") || Float.parseFloat(investment_field.getText())<1){
                JOptionPane.showMessageDialog(rootPane, "KINDLY DEFINE VALD VALUES");
            }
            else{
                switch(investmentMode){
                    case "Cash":
                        // <editor-fold defaultstate="collapsed" desc="Cash">
                        ps=cn.prepareStatement("SELECT TOP 1 balance FROM cashBook ORDER BY Id DESC");
                        rs=ps.executeQuery();
                        while(rs.next()){
                        balanceCashBook = rs.getFloat(1);
                        }
                        balanceCashBook=balanceCashBook+Float.parseFloat(investment_field.getText());
                        ps=cn.prepareStatement("INSERT INTO cashBook VALUES(GETDATE(),0,'"+ownerName_comboBox.getSelectedItem().toString()+"','Investment',"+investment_field.getText()+",'',"+balanceCashBook+")");
                        ps.execute();
    //                                    </editor-fold>
                        break;
                    case "Cheque":
                        // <editor-fold defaultstate="collapsed" desc="bankLedgerUpdate">
                        ps=cn.prepareStatement("SELECT bankId FROM bankList WHERE bankName='"+bankNameBox_owner.getSelectedItem().toString()+"'");
                        rs=ps.executeQuery();
                        while(rs.next()){
                            bankIdOwner=rs.getInt(1);
                        }
                        ps=cn.prepareStatement("SELECT TOP 1 balance,id FROM bankLedger WHERE bankId="+bankIdOwner+" ORDER BY id DESC");
                        rs=ps.executeQuery();
                        while(rs.next()){
                            bankBalanceOwner=rs.getFloat(1);
                        }
                        bankBalanceOwner=bankBalanceOwner+Float.parseFloat(investment_field.getText());
                        ps=cn.prepareStatement("INSERT INTO bankLedger VALUES("+bankIdOwner+",GETDATE(),0,'Investment',"+investment_field.getText()+",'',"+bankBalanceOwner+")");
                        ps.execute();
//            </editor-fold>
                        // <editor-fold defaultstate="collapsed" desc="Cheque">
                        ps=cn.prepareStatement("SELECT TOP 1 balance FROM chequeBook ORDER BY Id DESC");
                        rs=ps.executeQuery();
                        while(rs.next()){
                            balanceChequeBook=rs.getFloat(1);
                        }
                        balanceChequeBook=balanceChequeBook+Float.parseFloat(investment_field.getText());
                        ps=cn.prepareStatement("INSERT INTO chequeBook VALUES(GETDATE(),0,'"+bankNameBox_owner.getSelectedItem().toString()+"','"+ownerName_comboBox.getSelectedItem().toString()+"','Investment',"+investment_field.getText()+",'',"+balanceChequeBook+")");
                        ps.execute();
    //                                    </editor-fold>
                        break;
                }
                
                ps=cn.prepareStatement("UPDATE owners SET investment=investment+"+investment_field.getText()+"");
                ps.execute();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.getLocalizedMessage());
        }
        investment_field.setForeground(Color.GRAY);
        investment_field.setText("Investment");
        ownerName_comboBox.requestFocus();
    }//GEN-LAST:event_addOwnerActionPerformed

    private void investment_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_investment_fieldFocusGained
        focusGain(investment_field, "Investment");
    }//GEN-LAST:event_investment_fieldFocusGained

    private void investment_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_investment_fieldFocusLost
        focusLost(investment_field, "Investment");
    }//GEN-LAST:event_investment_fieldFocusLost

    private void Cheque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cheque3ActionPerformed
        bankNameBox_owner.setEnabled(true);
        investmentMode="Cheque";
    }//GEN-LAST:event_Cheque3ActionPerformed

    private void Cash3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash3ActionPerformed
        bankNameBox_owner.setEnabled(false);
        investmentMode="Cash";
    }//GEN-LAST:event_Cash3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Capital dialog = new Capital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cash3;
    private javax.swing.JRadioButton Cheque3;
    private javax.swing.JButton addOwner;
    public javax.swing.JComboBox bankNameBox_owner;
    private javax.swing.ButtonGroup buttonGro;
    private javax.swing.JTextField investment_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox ownerName_comboBox;
    // End of variables declaration//GEN-END:variables
}
