/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package al_qalam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad
 */
public class selectChalanFrame extends javax.swing.JInternalFrame {

    public static Connection conn() throws ClassNotFoundException,SQLException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url="jdbc:odbc:Al_Qalam";
        return DriverManager.getConnection(url,"sa","sa9" );
    }
    //  Connection Variables  
        Connection cn;
        ResultSet rs;
        PreparedStatement ps;
        Software abc;
        String clientName;
        
    
        // <editor-fold defaultstate="collapsed" desc="getChalanList.SetModel">
        DefaultListModel chL = new DefaultListModel();
        public void getChalanList(){
            try{
                cn=conn();
                ps=cn.prepareStatement("SELECT DISTINCT chalanNo FROM deliveryChalan WHERE invoiced='No' AND clientName='"+clientName+"'");
                rs=ps.executeQuery();
                while(rs.next()){
                    chL.addElement(rs.getString(1));
                }
                chalanList.setModel(chL);
            }
            catch(SQLException | ClassNotFoundException ex){
                JOptionPane.showMessageDialog(jScrollPane15, ex.getLocalizedMessage());
            }
            catch(NullPointerException e){
                
            }
        }
//        </editor-fold>
    /**
     * Creates new form selectChalanFrame
     */
    public selectChalanFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        chalanList = new javax.swing.JList();

        setClosable(true);

        jButton3.setText("Add Chalans");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane15.setViewportView(chalanList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Software.chalanNos = chalanList.getSelectedValuesList();
        Software.setSalesInvoice();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList chalanList;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane15;
    // End of variables declaration//GEN-END:variables
}
