package al_qalam;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.security.Key;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows XP
 */
public class SignUp extends javax.swing.JFrame {
        LogIn obj1 ;
        Cipher c;
        private Key key;
        String Pass,ab;
        KeyGenerator gn;
        Connection con;
        PreparedStatement ps;
        ResultSet rs;
        Statement st;
    /**
     * Creates new form Sign_up
     */
        
        public static Connection conn() throws ClassNotFoundException,SQLException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url="jdbc:odbc:Al_Qalam";
        return DriverManager.getConnection(url, "sa","sa9");
    }
    public SignUp() {
        initComponents();
        setLocation(320, 195);
        ImageIcon img =new ImageIcon("big_curved_arrow_right_up_red");
        setIconImage(img.getImage());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        copyRight = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserId = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        EmailId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();
        LogIn = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        copyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyRight.setText("© RHR_solutions");
        copyRight.setBounds(190, 290, 100, 14);
        jDesktopPane1.add(copyRight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        main_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 24), new java.awt.Color(0, 0, 102))))); // NOI18N
        main_panel.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Email_Id");

        UserId.setForeground(new java.awt.Color(153, 153, 153));
        UserId.setText("Write your Log_In Id here");
        UserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserIdFocusLost(evt);
            }
        });

        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("password");
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });

        EmailId.setForeground(new java.awt.Color(153, 153, 153));
        EmailId.setText("example@123mail.com");
        EmailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailIdFocusLost(evt);
            }
        });
        EmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailIdKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Log_In Id");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailId)
                    .addComponent(Password)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        main_panel.setBounds(10, 30, 280, 150);
        jDesktopPane1.add(main_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome2.png"))); // NOI18N
        SignUp.setToolTipText("Click Here To Sign Up");
        SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });
        SignUp.setBounds(10, 190, 275, 110);
        jDesktopPane1.add(SignUp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LogIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogIn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogIn.setText("Log In");
        LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });
        LogIn.setBounds(230, 10, 50, 20);
        jDesktopPane1.add(LogIn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ab-5.jpg"))); // NOI18N
        BackGround.setBounds(0, 0, 300, 320);
        jDesktopPane1.add(BackGround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void focusGain(JTextField txt,String s){
        if(txt.getText().equals(s)){
            txt.setText(null);
            txt.setForeground(Color.black);
        }else{
            txt.selectAll();
        }
    }
    public void focusLost(JTextField txt,String s){
        if(txt.getText().isEmpty()){
            txt.setText(s);
            txt.setForeground(Color.GRAY);
        }
    }
    private void UserIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserIdFocusGained
        // TODO add your handling code here:
        focusGain(UserId, "Write your Log_In Id here");
    }//GEN-LAST:event_UserIdFocusGained

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:
        focusGain(Password, "password");
    }//GEN-LAST:event_PasswordFocusGained

    private void EmailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusGained
        // TODO add your handling code here:
        focusGain(EmailId, "example@123mail.com");
    }//GEN-LAST:event_EmailIdFocusGained

    private void UserIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserIdFocusLost
        // TODO add your handling code here:
        focusLost(UserId, "Write your Log_In Id here");
    }//GEN-LAST:event_UserIdFocusLost

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
        focusLost(Password, "password");
    }//GEN-LAST:event_PasswordFocusLost

    private void EmailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusLost
        // TODO add your handling code here:
        focusLost(EmailId, "example@123mail.com");
    }//GEN-LAST:event_EmailIdFocusLost

    @SuppressWarnings("empty-statement")
    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
//        
//            Pass=Password.getText();
//            
//            try {                                    
//                c=Cipher.getInstance("DES/ECB/PKCS5Padding");
//                
//                c.init(Cipher.ENCRYPT_MODE, key);
//                
//                byte[] Encrypted = Pass.getBytes("UTF8");
//     
//                byte[] raw = c.doFinal(Encrypted);
//                
//                ab=raw.toString();
//                gn= KeyGenerator.getInstance("DES");
//                gn.init(new SecureRandom());
//                key=gn.generateKey();
//                
//                } catch (IllegalBlockSizeException ex) {
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (BadPaddingException ex) {
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (UnsupportedEncodingException ex) {
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (InvalidKeyException ex) {
//                    JOptionPane.showMessageDialog(rootPane, ex);
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (NoSuchAlgorithmException ex) {
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (NoSuchPaddingException ex) {
//                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            System.out.print(ab);
                try {
                    if(!"Write your Log_In Id here".equals(UserId.getText()) && !"password".equals(Password.getText()) && !"example@123mail.com".equals(EmailId.getText())){
                        con=conn();
                        ps=con.prepareStatement("Insert into signUp values('"+UserId.getText()+"','"+Password.getText()+"','"+EmailId.getText()+"')");
                        ps.execute();
                        this.setVisible(false);
                        obj1=new LogIn();
                        obj1.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Sign Up requires all details");
                    }
                    
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                }
                
    }//GEN-LAST:event_SignUpMouseClicked

    private void EmailIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIdKeyPressed
        // TODO add your handling code here:
        int key1=evt.getKeyCode();
        if (key1 == KeyEvent.VK_ENTER){
            SignUpMouseClicked(null);
    }
    }//GEN-LAST:event_EmailIdKeyPressed

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        LogIn abc = new LogIn();
        this.setVisible(false);
        abc.setVisible(true);
    }//GEN-LAST:event_LogInMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (    ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JTextField EmailId;
    private javax.swing.JLabel LogIn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SignUp;
    private javax.swing.JTextField UserId;
    private javax.swing.JLabel copyRight;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel main_panel;
    // End of variables declaration//GEN-END:variables
}

